database setup with docker
skaarkzo-capstone/core-backend pull request #4
Opened 2024-11-15 20:30 UTC by rakhshankhan

# JIRA Link

https://skaarkzo-capstone.atlassian.net/browse/SUSTAIN-52

# Summary of Changes

- Added docker-compose to initialize db container
- Added health check to make sure service doesn't start without db running

2024-11-15 21:18 UTC, zaidokal requested changes

2024-11-15 21:20 UTC, rakhshankhan commented on app/core/config.py
> +    MONGO_DB: str = "sustain-db"
I made an environment variables files originally while doing it. Realized not necessary since everyone is gonna be running the db locally.

2024-11-15 21:39 UTC, zaidokal commented on app/core/config.py
> +    MONGO_DB: str = "sustain-db"
Okay makes sense.

2024-11-15 21:40 UTC, zaidokal approved these changes

2024-11-16 00:37 UTC, skhan943 approved these changes
Love the connection attempt logic :)

2024-11-16 00:41 UTC, arhamansarii approved these changes

2024-11-16 00:42 UTC, merged