Sustain 245-246: Added pipeline to call scraper service
skaarkzo-capstone/core-backend pull request #7
Opened 2024-12-03 04:11 UTC by rakhshankhan

# JIRA Ticket Link

https://skaarkzo-capstone.atlassian.net/browse/SUSTAIN-245
https://skaarkzo-capstone.atlassian.net/browse/SUSTAIN-246

# Summary of Changes

- Added service logic to handle sending request to data scraper service.
- Added controller logic for LLM to call to retrieve scraped data.

2024-12-03 14:45 UTC, skhan943 requested changes
Generally looks good, minor fixes

2024-12-03 14:45 UTC, skhan943 commented on app/service/search_service.py
>      return SearchDTO(companyName=input_text)
Can we standardize company_name

2024-12-03 14:45 UTC, skhan943 commented on app/core/config.py
> +    MAX_TIMEOUT: Timeout = Timeout(None)
Please explain the timeout a bit more with a comment, thanks!

2024-12-03 23:34 UTC, zaidokal requested changes

2024-12-03 23:34 UTC, zaidokal commented on app/service/scraper_service.py
> +        url = f"{settings.SCRAPER_BASE_URL}/api/scraper/company/"
Let's put all the URLs in the settings file? Including the /api/scraper/company. 

Could do something like this in the settings file:
export const API_ENDPOINTS = {
    SINGLE_COMPANY: `${API_BASE_URL}/company`,
    SCRAPER_API: `${API_BASE_URL}/api/scraper/company`
}

2024-12-03 23:34 UTC, zaidokal commented on app/service/scraper_service.py
> +        url = f"{settings.SCRAPER_BASE_URL}/api/scraper/company/"
Also can we change the one to call the database? It is currently http://localhost:8000/api/main/companies, its too similar to /company

2024-12-04 02:20 UTC, zaidokal approved these changes

2024-12-04 19:26 UTC, skhan943 approved these changes

2024-12-04 20:33 UTC, merged