Added company delete functionality
skaarkzo-capstone/core-backend pull request #9
Opened 2024-12-27 09:27 UTC by zaidokal

# JIRA Ticket Link

https://skaarkzo-capstone.atlassian.net/browse/SUSTAIN-263

# Summary of Changes

Added delete company functionality

2024-12-27 20:20 UTC, rakhshankhan approved these changes

2024-12-28 04:40 UTC, skhan943 submitted a review, later dismissed

2024-12-29 01:35 UTC, arhamansarii submitted a review, later dismissed
LGTM!

2024-12-29 01:44 UTC, rakhshankhan requested changes
mark this MR as draft pls

2024-12-29 20:22 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
don't need this logic, i think any message (success or error) should be handled in frontend.

2024-12-29 20:22 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            "message": message,
```suggestion
```

2024-12-29 20:24 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
accidentally forgot to mention that for toggle compliance too. it's been merged, so will have to change later (or create new MR changing that)

2024-12-29 23:24 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
We use these messages in the frontend

2024-12-29 23:24 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            "message": message,
Outdated. Please look at the latest changes

2024-12-29 23:37 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
these endpoints will need to be refactored to only return success and not successful deletions. logic to display the proper message will be done directly in the frontend rather than having the backend handling different messages.

2024-12-30 00:54 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
The issue with that is if at any point it fails, we will just know it failed with no details. Especially with the multiple companies part, as in if 1 fails it will send back an error saying failure. It will be better to have more details to pass on.

2024-12-30 01:12 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            await CompanyService.delete_companies(company_ids)
delete_companies is taking the whole company_ids array rather than the success_deletions? wouldn't that be deleting all the company_ids after checking success_deletions is not null?

2024-12-30 01:12 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +                {"name": name, "id": cid} for name, cid in success_deletions
rather than appending a tuple to success_deletions and then doing this mapping logic here, why not append a json object with name and id and use the success_deletions array here?

2024-12-30 01:16 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
after reading thru the code, we'll know which companies failed since they're being returned in the response. regardless, it's not good practice to have frontend related messages being handled by the backend.

2024-12-30 05:34 UTC, zaidokal commented on app/service/company_service.py
> +    async def get_evaluated_company_by_id(company_id: ObjectId):
Done

2024-12-30 05:34 UTC, zaidokal commented on app/service/company_service.py
> +        company = await evaluated_companies_collection.find_one({"name": company_name})
Done

2024-12-30 05:39 UTC, zaidokal commented on app/model/dto/company_evaluated_dto.py
> +    id: str
Removed

2024-12-30 05:48 UTC, zaidokal commented on app/service/company_service.py
Done

2024-12-30 05:57 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +                {"name": name, "id": cid} for name, cid in success_deletions
Done

2024-12-30 06:01 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            await CompanyService.delete_companies(company_ids)
Done

2024-12-30 06:05 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            "message": message,
Not sure what you mean here

2024-12-30 06:05 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            "message": message,
Not sure what you mean here

2024-12-30 06:49 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +            "message": message,
Remove the message from the response. Only return successful and non-successful deletions.

2024-12-31 04:30 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +    success_toggles = []
```suggestion
    failed_companies = []
    valid_companies = []
```

2024-12-31 04:30 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +    success_deletions = []
```suggestion
    failed_companies = []
    valid_companies = []
```

2024-12-31 04:30 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +
Need error handling for when company was found but failed due to another reason
```suggestion
except Exception as e:
                failed_companies.append({"id": company_request.id, "reason": str(e)})
```

2024-12-31 04:36 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
Done

2024-12-31 04:36 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            "message": message,
Done

2024-12-31 04:36 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            message = "No companies were updated."
Done

2024-12-31 04:36 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            "message": message,
Done

2024-12-31 04:38 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            message = "No companies were deleted."
Done

2024-12-31 04:41 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            success_deletions.append({"name": company["name"], "id": str(company_id)})
I think keeping this as success_deletions makes more sense than valid_companies

2024-12-31 04:46 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +
Already done, mind checking again?

2024-12-31 04:54 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +    success_toggles = []
Renamed

2024-12-31 04:54 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +    success_deletions = []
Renamed

2024-12-31 04:54 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +            success_deletions.append({"name": company["name"], "id": str(company_id)})
Renamed

2024-12-31 04:55 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +                failed_deletions.append(f"Company with ID '{company_id}' not found.")
Done

2024-12-31 05:57 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +    try:
```suggestion
    @router.delete("/delete-companies")
async def delete_companies(request: List[CompanyRequest]):
    company_ids = [ObjectId(company_request.id) for company_request in request]
    failed_companies = []
    valid_companies = []

    for company_id in company_ids:
        try:

            if not ObjectId.is_valid(company_id):
                failed_companies.append({"id": company_id, "reason": "Invalid ID: {company_id}"})
                raise HTTPException(status_code=400, detail=f"Invalid ID: {company_id}")

            # Fetch the company by ID
            company = await CompanyService.get_evaluated_company(company_id)

            if company:
                valid_companies.append({"id": str(company_id), "name": company["name"]})
            else:
                failed_companies.append({"id": company_id, "reason": "Company not found"})
                raise HTTPException(status_code=404, detail=f"Company not found: {company_id}")

        except Exception as e:

            failed_companies.append({"id": company_id, "reason": str(e)})
            raise HTTPException(status_code=500, detail=f"An error occurred: {str(e)}")

    try:
        # If there are valid companies to delete, pass them to the service
        if valid_companies:
            valid_company_ids = [ObjectId(company["id"]) for company in valid_companies]
            await CompanyService.delete_companies(valid_company_ids)

        return {
            "success": valid_companies,
            "failed": failed_companies
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={
                "message": f"An error occurred while deleting companies: {str(e)}",
                "success": valid_companies,
                "failed": failed_companies,
            },
        )
```

2024-12-31 05:57 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +    try:
I think doing exception handling as provided above would be a better way. Usually running a loop on try catch should be avoided, but it'll make things more difficult, so we can keep it.

2024-12-31 06:01 UTC, zaidokal commented on app/api/main/controller/company_controller.py
> +    try:
Done

2024-12-31 06:51 UTC, rakhshankhan commented on app/api/main/controller/company_controller.py
> +    except Exception as e:
This try/except block should be handling toggle compliance logic. First try catch block handles getting valid companies. Very similar to delete companies implementation.

2024-12-31 07:29 UTC, arhamansarii approved these changes

2024-12-31 07:38 UTC, arhamansarii approved these changes
I trust Rakhshan's thorough and intricate review.

2024-12-31 20:35 UTC, arhamansarii submitted a review, later dismissed

2024-12-31 21:03 UTC, rakhshankhan approved these changes

2024-12-31 21:04 UTC, arhamansarii approved these changes

2024-12-31 21:04 UTC, merged